### ISSUE TITLE
Data not updating properly

### ISSUE THREAD

**Issue by ujwalchordiya** [marciovalim/realtime_pagination#1]
When a document from the list is modified/deleted from firebase, the data is shuffled.

**Comment by marciovalim** [comment]
Are you using orderBy in the query?

**Comment by ujwalchordiya** [comment]
Hi.  Thank you for your response.

Yes. I'm using it.

So basically when I remove any document on firestore, the data is shifted
to one document up.

Example:

From a list of 100 documents, if I delete document number 20, I'm seeing
data of document 22nd in 20th position.

**Comment by marciovalim** [comment]
Ok, can you post the code and a screenshot of the collection in the firebase console?

**Comment by ujwalchordiya** [comment]
Sure. Give me sime time. I'll send you

**Comment by reanyouda** [comment]
it not working when you set state to get query

**Comment by marciovalim** [comment]
@ujwalchordiya any update? I tried this in my current project and it's working normally. Firebase usually shuffles documents whenever a deletion occurs. But using orderBy in the query, it ensures that the order will be maintained.
So a screenshot would be really useful.

**Comment by marciovalim** [comment]
@reanyouda is this a different issue? If so, please open another one.

**Comment by xanf-code** [comment]
Ordering my timeline with timestamp and on CRUD everything works fine 👍

**Comment by ujwalchordiya** [comment]
> @ujwalchordiya any update? I tried this in my current project and it's working normally. Firebase usually shuffles documents whenever a deletion occurs. But using orderBy in the query, it ensures that the order will be maintained.
> So a screenshot would be really useful.

Apologies for the delayed response. 
The pagination works fine if no documents are modified. So for instance, if I fetch 10 documents 5 times, so 5 pages, the results work. But if I delete say document 25, all the results are shifted up and get mixed up.
