### ISSUE TITLE
Access to the _scrollController

### ISSUE THREAD

**Issue by buzzicards** [marciovalim/realtime_pagination#3]
I like to have access to the _scrollController so i can determine if the scroll position has changed so i can show icon to jump /animate to bottom of my list. 

Is this possible with this package? 

Thanks

**Comment by marciovalim** [comment]
Hi @buzzicards , I'll add an option to pass your own instance of scrollController.

**Comment by marciovalim** [comment]
Already added. Please text me back if your problem has been solved.

**Comment by buzzicards** [comment]
Thanks that works
