### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by elmissouri16** [marciovalim/realtime_pagination#4]
hi first of all thanks for the amazing package its help me a lot with the app I work on, I was wondering if they are plans for exposing  listview proprieties such as physics, padding .. from the RealTimePagination widget to have full control over it , I  had this use code and I hade to fork your project and add it on the code but I didn't expose it outside if  there are plans for it or you think its something  will be good I can implement it and do pr in next days,

**Comment by marciovalim** [comment]
Hi @elmissouri16, I used a builder approach to add all these features at once. 
You can check the new documentation in the readme file. 
Hope it helps you!

Please try the new version and close the issue if the problem has been solved.

**Comment by elmissouri16** [comment]
oh yeah sorry didn't notice it, I already use the latest version

**Comment by marciovalim** [comment]
@elmissouri16 I have something to talk to you about. Do you have a minute? If you do, please send me a message at marciogsvalim@gmail.com

**Comment by elmissouri16** [comment]
> @elmissouri16 I have something to talk to you about. Do you have a minute? If you do, please send me a message at [marciogsvalim@gmail.com](mailto:marciogsvalim@gmail.com)

yeah sure
