### ISSUE TITLE
Package Will Not Compile

### ISSUE THREAD

**Issue by jmsquillaro** [marciovalim/realtime_pagination#5]
This seems like a wonderful package that will help me and so many other developers with their projects, so thank you for making it! However, currently it is sadly unusable as when added to a project, it won't even compile. On iOS, this is the outputs we are getting:
```
 ../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/realtime_pagination-0.0.7/lib/realtime_pagination.dart:158:15: Error: The argument type 'RealtimePaginationCubit' can't be assigned to the parameter type 'Stream<RealtimePaginationState>'.
     - 'RealtimePaginationCubit' is from 'package:realtime_pagination/cubits/realtime_pagination_cubit.dart' ('../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/realtime_pagination-0.0.7/lib/cubits/realtime_pagination_cubit.dart').
     - 'Stream' is from 'dart:async'.
     - 'RealtimePaginationState' is from 'package:realtime_pagination/cubits/realtime_pagination_state.dart' ('../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/realtime_pagination-0.0.7/lib/cubits/realtime_pagination_state.dart').
          stream: _realtimePaginationCubit,
                  ^
    Command PhaseScriptExecution failed with a nonzero exit code
```

To back this up, the package is also failing the static code check on Pub.dev citing the same issues. Can or will this be fixed (and if so, do you have a rough estimate as to when) as I know many would be willing to use this package if it can work. Also, will the package be migrating to null safety? Thank you for your hard work!

**Comment by marciovalim** [comment]
Hi @jmsquillaro, thank you for letting me know. Fixed and upgraded to null-safety. Please check if it's working for you.

**Comment by jmsquillaro** [comment]
It works perfectly @marciovalim! Thank you again for your hard work on such a great package!
