### ISSUE TITLE
Some docs are missing

### ISSUE THREAD

**Issue by vppysk** [marciovalim/realtime_pagination#7]
Hi, Thank you for providing this package!

I am fetching data from firestore and displaying it.
If the number of documents in the firestore is large, documents in the middle may be missing.

The following image is an example.
Documents are displayed in descending order by timestamp, but there are actually many documents between 2021-04-01 22:00:51.002 and 2020-12-21 17:49:40.029

![Screenshot_20210519-223711](https://user-images.githubusercontent.com/33174374/118823722-278cc500-b8f4-11eb-8b69-d666edca20c7.png)

**Comment by marciovalim** [comment]
Hi, @vppysk. Can you give me more information? How many documents are in your full list? And how many items per page are you loading?

**Comment by vppysk** [comment]
Hi, @marciovalim.
I have about 5400 documents.
And I've set itemsPerPage to 10, 20, and 30.

Let me know if there's any other information you need.

**Comment by marciovalim** [comment]
@vppysk  Are you using a database just for testing? If I could have access to your database it would be easier.

**Comment by vppysk** [comment]
@marciovalim 
I'm sorry for the late reply. I'm using the database for testing, but it's a company one, so it's hard to grant you access to it.
I've come up with another way to use pagenatie_firestore, so I'll try that one.
Thank you for responding !
